# This package will contain the spiders of your Scrapy project
#
# Please refer to the documentation for information on how to create and manage
# your spiders.

import scrapy

from os_scrapy_kafka_pipeline.items import ExampleItem


class ExampleSpider(scrapy.Spider):
    """ ExampleSpider
    Auto generated by os-scrapy-cookiecuter

    Run:
        scrapy crawl example
    """

    name = "example"

    start_urls = ["http://example.com/"]

    def parse(self, response):
        yield ExampleItem(
            url=response.url,
            status=response.status,
            headers=response.headers,
            meta=response.meta,
            body=response.body,
        )
